apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.fastapi.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.fastapi.name }}
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.fastapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.fastapi.name }}
    spec:
      serviceAccountName: {{ .Values.fastapi.serviceAccount.name }}
      containers:
        - name: {{ .Values.fastapi.name }}
          image: {{ .Values.fastapi.image }}
          imagePullPolicy: Always
          resources:
          {{- toYaml .Values.fastapi.resources | nindent 10 }}
          ports:
            - containerPort: {{ .Values.fastapi.containerPort }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MODEL_DISPLAY_NAME
              value: "{{ .Values.fastapi.modelDisplayName }}"
            - name: VLLM_LABEL_SELECTOR
              value: "app={{ .Release.Name }}-{{ .Values.vllm.name }}"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.fastapi.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.fastapi.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
