apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.fastapi.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.fastapi.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.fastapi.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.fastapi.containerPort }}
      protocol: TCP
