{{- if and .Values.ingress.enabled (eq .Values.ingress.type "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-{{ .Values.fastapi.name }}-traefik
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-{{ .Values.fastapi.name }}
          port: 80
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
